name: ci

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF##*/}
            echo ::set-output name=tag_name::${TAG}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        run: docker login -u abhishek138 -p ${{ secrets.DOCKER_TOKEN }}
      - name: build and publish image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./11/buster/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            abhishek138/docker-agent:${{ steps.prepare.outputs.tag_name }}
            abhishek138/docker-agent:latest
            
            
